const wokeStatements = [
    "Breakfast is woke",
    "Jogging is woke",
    "Drinking water is woke",
    "Using umbrellas is woke",
    "Breathing oxygen is woke",
    "Wearing socks is woke",
    "Blinking is woke",
    "Grocery shopping is woke",
    "Having a bedtime is woke",
    "Owning a couch is woke",
    "Brushing your teeth is woke",
    "Tying your shoes is woke",
    "Walking your dog is woke",
    "Using calculators is woke",
    "Reading books is woke",
    "Sleeping at night is woke",
    "Taking showers is woke",
    "Parallel parking is woke",
    "Posting on social media is woke",
    "Eating vegetables is woke",
    "Wearing glasses is woke",
    "Having a birthday is woke",
    "Doing laundry is woke",
    "Drinking coffee is woke",
    "Using crosswalks is woke",
    "Setting alarms is woke",
    "Owning furniture is woke",
    "Paying taxes is woke",
    "Making toast is woke",
    "Getting haircuts is woke",
    "Riding bicycles is woke",
    "Listening to music is woke",
    "Wearing hats is woke",
    "Using telephones is woke",
    "Walking upstairs is woke",
    "Gardening is woke",
    "Charging your phone is woke",
    "Writing emails is woke",
    "Recycling is extremely woke",
    "Vacation time is woke",
    "Wearing sunscreen is woke",
    "Having a job is woke",
    "Driving cars is woke",
    "Owning pets is woke",
    "Having windows is woke",
    "Wearing shoes is woke",
    "Having a refrigerator is woke",
    "Using electricity is woke",
    "Having doors is woke",
    "Breathing air is woke",
    "Saying 'hello' is woke",
    "Eating lunch is woke",
    "Owning a clock is woke",
    "Using a calendar is woke",
    "Having opinions is woke",
    "Buying groceries is woke",
    "Watching TV is woke",
    "Using light bulbs is woke",
    "Having running water is woke",
    "Drinking milk is woke",
    "Kale is woke",
    "Coding is woke",
    "Traffic circles are woke",
    "Paying child support is woke",
    "Pumpkin spice is woke",
    "Wearing scarves is woke",
    "Using microwaves is woke",
    "Having a mailbox is woke",
    "Solar panels are woke",
    "Wearing gloves is woke",
    "Using elevators is woke",
    "Learning history is woke",
    "Meal kits are woke",
    "Star Wars is woke",
    "Astrology is woke",
    "Wearing masks is woke",
    "Having a passport is woke",
    "Using credit cards is woke",
    "Having a driver's license is woke",
    "Wearing watches is woke",
    "Using GPS is woke",
    "Having a library card is woke",
    "Using public transportation is woke",
    "Childhood immunizations are woke",
    "Flossing is woke",
    "Tip jars are woke",
];  